tap "cloudflare/cloudflare"
tap "d12frosted/emacs-plus"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mas-cli/tap"
tap "mattiaslundberg/fastjump"
tap "universal-ctags/universal-ctags"
brew "ansible"
brew "antigen"
brew "autoconf"
brew "automake"
brew "coreutils"
brew "libtool"
brew "unixodbc"
brew "asdf"
brew "autojump"
brew "aws-iam-authenticator"
brew "awscli"
brew "bat"
brew "python"
brew "clisp"
brew "cmake"
brew "curl"
brew "editorconfig"
brew "entr"
brew "exa"
brew "exercism"
brew "fd"
brew "fzf"
brew "gdb"
brew "ghi"
brew "git"
brew "git-extras"
brew "git-quick-stats"
brew "gmp"
brew "gnu-sed"
brew "go"
brew "graphviz"
brew "icu4c"
brew "harfbuzz"
brew "htop"
brew "httpie"
brew "hub"
brew "jq"
brew "jsonnet"
brew "kompose"
brew "libmagic"
brew "libxslt"
brew "protobuf"
brew "mosh"
brew "ncdu"
brew "neofetch"
brew "pipenv"
brew "postgresql"
brew "prettyping"
brew "pv"
brew "pwgen"
brew "pyenv"
brew "pyenv-virtualenv"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "rustup-init"
brew "td"
brew "texinfo"
brew "the_silver_searcher"
brew "tldr"
brew "tmux"
brew "watch"
brew "watchman"
brew "wxmac"
brew "zsh"
brew "cloudflare/cloudflare/cloudflared"
brew "d12frosted/emacs-plus/emacs-plus"
brew "mas-cli/tap/mas"
brew "mattiaslundberg/fastjump/fastjump"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "authy"
cask "bartender"
cask "bettertouchtool"
cask "bitwarden"
cask "carbon-copy-cloner"
cask "coconutbattery"
cask "dash"
cask "docker"
cask "fantastical"
cask "firefox"
cask "font-source-code-pro"
cask "gimp"
cask "google-chrome"
cask "gpg-suite"
cask "iterm2"
cask "karabiner-elements"
cask "kitematic"
cask "ngrok"
cask "spotify"
cask "tableplus"
cask "vagrant"
cask "visual-studio-code"
mas "AdGuard for Safari", id: 1440147259
mas "Amphetamine", id: 937984704
mas "Easy Pomodoro", id: 1439714447
mas "GarageBand", id: 682658836
mas "GIPHY CAPTURE", id: 668208984
mas "iMovie", id: 408981434
mas "Just Focus", id: 1142151959
mas "Keynote", id: 409183694
mas "Lightshot Screenshot", id: 526298438
mas "Night Eye", id: 1450504903
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "The Unarchiver", id: 425424353
mas "Trello", id: 1278508951
