---
- hosts: [dev]
  become: false

  roles:
    - role: elixir
    - role: python
    - role: docker

  before_tasks:
    - name: Install base packages
      become: true
      apt:
        state: present
        update_cache: true
        name:
          - zlib1g-dev
          - make
          - clang
          - unzip
          - libssl-dev
          - editorconfig
          - rustc
          - entr
          - vim
          - zsh
          - git
          - llvm
          - autoconf
          - fd-find
          - ripgrep

    - name: Symlink fd
      file:
        state: link
        src: "/usr/bin/fdfind"
        dest: "/usr/bin/fd"

    - name: Install snaps
      command: "snap install --classic {{ item }}"
      with_items:
        - universal-ctags
      become: yes

    - name: Copy ssh key
      copy:
        src: ~/.ssh/id_git
        dest: ~/.ssh/id_ed25519
        mode: 0600

    - name: bashrc
      copy:
        src: bashrc
        dest: ~/.bashrc
