---
- hosts: [workstation]
  become: true

  tasks:
    - name: Read settings
      include_vars:
        file: settings.yaml
        name: settings
         
    - name: Ensure download directory exists
      file:
        state: directory
        path: /tmp/hosts

    - name: Download hosts block file
      get_url:
        url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
        dest: /etc/hosts

    - name: Add localhost
      lineinfile:
        path: /etc/hosts
        insertafter: "127.0.0.1 localhost"
        line: "127.0.0.1 {{ ansible_hostname }}"

    - name: Add custom records
      lineinfile:
        path: /etc/hosts
        insertafter: "127.0.0.1 {{ ansible_hostname }}"
        line: "{{ item }}"
      with_items: "{{ settings.custom_records }}"

    - name: Add blocked sites
      lineinfile:
        path: /etc/hosts
        line: "0.0.0.0 {{ item }}"
      with_items: "{{ settings.blocked_sites }}"
