---
- hosts: all
  become: true

  tasks:
    - name: Download hosts file
      get_url:
        url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
        dest: /etc/hosts

    - name: Add localhost
      lineinfile:
        path: /etc/hosts
        insertafter: "127.0.0.1 localhost"
        line: "127.0.0.1 {{ ansible_hostname }}"

    - name: Read settings
      include_vars:
        file: settings.yaml
        name: settings

    - name: Add blocked sites
      lineinfile:
        path: /etc/hosts
        line: "0.0.0.0 {{ item }}"
      with_items: "{{settings.blocked_sites}}"
