---
- hosts: all
  become: false

  tasks:
    - name: Install custom packages
      become: true
      apt:
        state: present
        name:
          - openconnect
          - vim
          - python3-pip
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - socat

    - name: Install pipenv
      pip:
        executable: pip3
        name: pipenv
