---
- hosts: all
  become: false
  vars:
    - packages_state: present

  roles:
   - role: workstation

  pre_tasks:
    - name: Upgrade pacman packages
      become: yes
      pacman:
        update_cache: yes
      when: ansible_os_family == "Archlinux"
