---
- hosts: workstation
  become: false

  roles:
    - role: base
    - role: keyboard
    - role: asdf
      vars:
        lang: nodejs
    - role: asdf
      vars:
        lang: terraform
    - role: elixir
    - role: kotlin
    - role: python
    - role: docker
    - role: dotfiles
    - role: settings
