---
- hosts: unifi
  become: false

  tasks:
    - name: Copy install script
      get_url:
        url: https://raw.githubusercontent.com/mattiaslundberg/dotfiles/master/bin/pi_install_unifi
        dest: ~/pi_install_unifi

    - name: Run install script
      command: ~/pi_install_unifi

    - name: Install dependencies
      become: true
      command: apt-get install --fix-broken

    - name: Restart unifi
      become: true
      systemd:
        name: unifi
        state: restarted
