---
- hosts: all
  become: false
  vars:
    - packages_state: latest

  roles:
   - role: workstation

  tasks:
    - name: Upgrade pacman packages
      pacman:
        upgrade: true
        update_cache: yes
      when: ansible_os_family == "Archlinux"

    - name: Upgrade aur packages
      command: pacaur --noedit --noconfirm -Syu
      when: ansible_os_family == "Archlinux"

    - name: Upgrade brew packages
      homebrew:
        update_homebrew: yes
        upgrade_all: yes

  pre_tasks:
    - name: Set python for MacOS
      set_fact:
        ansible_python_interpreter: /usr/local/bin/python
      when: ansible_os_family == "Darwin"
