---
- name: Create linux symlinks
  file:
    state: link
    src: "~/.dotfiles/{{ item }}"
    dest: "~/{{ item }}"
  with_items:
    - .keymap.xkb
    - .xsessionrc
  tags: [keyboard]
  when: ansible_os_family == "Debian"
