---
- name: Clone dotfiles repo
  git:
    dest: ~/.dotfiles
    repo: "git@github.com:mattiaslundberg/dotfiles.git"
    recursive: yes
    accept_hostkey: yes
  ignore_errors: yes

- name: Clone doom-emacs repo
  git:
    dest: ~/.emacs.d
    repo: "git@github.com:hlissner/doom-emacs.git"
    accept_hostkey: yes
  ignore_errors: yes
  tags: [emacs]

- name: Remove default bashrc
  file:
    state: absent
    dest: ~/.bashrc
  tags: [dotfiles]

- name: Remove default zshrc
  file:
    state: absent
    dest: ~/.zshrc
  tags: [dotfiles]

- name: Create common symlinks
  file:
    state: link
    src: "~/.dotfiles/{{ item }}"
    dest: "~/{{ item }}"
  with_items:
    - .editorconfig
    - .aliases
    - .bashrc
    - .zshenv
    - .zprofile
    - .zlogin
    - .zshrc
    - .gitignore_global
    - .screenrc
    - .tmux.conf
    - .doom.d
    - .gitconfig
    - .rgignore
    - .iex.exs
  tags:
    - dotfiles
    - emacs
    - tmux

- name: Symlink bin
  file:
    state: link
    src: ~/.dotfiles/bin
    dest: ~/.bin

- name: Install doom-emacs
  command: ~/.emacs.d/bin/doom -y install
  args:
    creates: ~/.emacs.d/.local/env
  tags: [emacs]

- name: Install Tmux Plugin Mangaer
  git:
    dest: ~/.tmux/plugins/tpm
    repo: "git@github.com:tmux-plugins/tpm.git"
    recursive: yes
    accept_hostkey: yes
    update: no
  tags: [tmux]

- name: Install all tmux plugins
  command: ~/.tmux/plugins/tpm/scripts/install_plugins.sh
  tags: [tmux]

- name: Zsh plugin manager
  git:
    dest: ~/.zinit/bin
    repo: "https://github.com/zdharma/zinit.git"
    accept_hostkey: yes
    update: no
  tags: [dotfiles, zsh, install]
