---
- name: Clone dotfiles repo
  git:
    dest: ~/.dotfiles
    repo: "git@github.com:mattiaslundberg/dotfiles.git"
    recursive: yes
    accept_hostkey: yes
  ignore_errors: yes

- name: Clone doom-emacs repo
  git:
    dest: ~/.emacs.d
    repo: "git@github.com:hlissner/doom-emacs.git"
    accept_hostkey: yes
  tags: [emacs]

- name: Check default bashrc
  stat:
    path: ~/.bashrc
  register: bashrc
  tags: [dotfiles]

- name: Remove default bashrc
  file:
    state: absent
    dest: ~/.bashrc
  when: not bashrc.stat.islnk
  tags: [dotfiles]

- name: Check default zshrc
  stat:
    path: ~/.zshrc
  register: zshrc
  tags: [dotfiles]

- name: Remove default zshrc
  file:
    state: absent
    dest: ~/.zshrc
  when: not zshrc.stat.islnk
  tags: [dotfiles]

- name: Create common symlinks
  file:
    state: link
    src: "~/.dotfiles/{{ item }}"
    dest: "~/{{ item }}"
  with_items:
    - .editorconfig
    - .aliases
    - .bashrc
    - bin
    - .zshenv
    - .zprofile
    - .zlogin
    - .zshrc
    - .gitignore_global
    - .screenrc
    - .tmux.conf
    - .doom.d
    - .gitconfig
    - .tool-versions
    - .rgignore
    - .iex.exs
  tags:
    - dotfiles
    - emacs
    - tmux

- name: Install doom-emacs
  command: ~/.emacs.d/bin/doom -y install
  args:
    creates: ~/.emacs.d/.local/env
  tags: [emacs]

- name: Create ctags config directory
  file:
    state: directory
    dest: ~/.ctags.d/
  tags: [ctags, emacs]

- name: Symlink new ctags config
  file:
    state: link
    src: ~/.dotfiles/.ctags
    dest: ~/.ctags.d/default.ctags
  tags: [ctags, emacs]

- name: Install Tmux Plugin Mangaer
  git:
    dest: ~/.tmux/plugins/tpm
    repo: "git@github.com:tmux-plugins/tpm.git"
    recursive: yes
    accept_hostkey: yes
    update: no
  tags: [tmux]

- name: Zsh plugin manager
  git:
    dest: ~/.zinit/bin
    repo: "https://github.com/zdharma/zinit.git"
    accept_hostkey: yes
    update: no
  tags: [dotfiles, zsh, install]
