---
- name: Symlink karabiner config
  file:
    state: link
    src: ~/.dotfiles/.config/karabiner
    dest: ~/.config/karabiner
  tags: [karabiner, keyboard]

- name: Symlink spacehammer config
  file:
    state: link
    src: "~/.dotfiles/.spacehammer"
    dest: "~/.spacehammer"
  tags: [spacehammer]

- name: Clone spacehammer repo
  git:
    dest: ~/.hammerspoon
    repo: "git@github.com:agzam/spacehammer.git"
    recursive: yes
    accept_hostkey: yes
    update: yes
  ignore_errors: yes
  tags: [spacehammer]

- name: Install fennel
  command: luarocks install --local fennel
  args:
    creates: ~/.luarocks/bin/fennel
  tags: [spacehammer]

- name: Load iterm color schemes
  command: "open {{ item }}.itermcolors"
  with_items:
    - AtomOne
    - AtomOneLight
  tags: [iterm]
