---
- name: Install asdf plugins
  command: "asdf plugin-add {{ item }}"
  args:
    creates: "~/.asdf/plugins/{{ item }}"
  tags: [asdf]
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ lookup('env', 'HOME') }}/.asdf/bin:/home/mattias/.asdf/bin"
  with_items:
    - elixir
    - erlang
    - nodejs
    - terraform

- name: Load nodejs key
  command: bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
  tags: [asdf]

- name: Install latest version of everything managed by asdf
  shell: "asdf plugin-list | xargs -I _ asdf install _ latest "
  tags: [asdf]
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ lookup('env', 'HOME') }}/.asdf/bin"
