---
- name: Create configuration folder
  become: yes
  file:
    dest: /usr/local/etc/cloudflared/
    state: directory
  tags: [dns]

- name: Create configuration file
  become: yes
  template:
    dest: /usr/local/etc/cloudflared/config.yml
    src: templates/cloudflare.yml.j2
  tags: [dns]

- name: Enable service
  become: yes
  command: cloudflared service install
  tags: [dns]

- name: Ensure service started
  become: yes
  command: launchctl start com.cloudflare.cloudflared
  tags: [dns]

- name: Set local DNS for all Wi-Fis
  command: networksetup -setdnsservers Wi-Fi 127.0.0.1
  tags: [dns]
