---
- name: Clone dotfiles repo
  git:
    dest: ~/.dotfiles
    repo: "git@github.com:mattiaslundberg/dotfiles.git"
    recursive: yes
    accept_hostkey: yes
    update: yes
  ignore_errors: yes

- name: Clone doom-emacs repo
  git:
    dest: ~/.emacs.d
    repo: "git@github.com:hlissner/doom-emacs.git"
    accept_hostkey: yes
    update: yes
  tags: [emacs, spacemacs]

- name: Remove default bashrc
  file:
    state: absent
    dest: ~/.bashrc
  tags: [dotfiles]

- name: Create common symlinks
  file:
    state: link
    src: "~/.dotfiles/{{ item }}"
    dest: "~/{{ item }}"
  with_items:
    - .editorconfig
    - .aliases
    - .bashrc
    - bin
    - .zsh
    - .zshenv
    - .zprofile
    - .zlogin
    - .zshrc
    - .gitignore_global
    - .hgrc
    - .inputrc
    - .screenrc
    - .sshrc
    - .sshrc.d
    - .vimsnippets
    - .spacemacs
    - .fastjump.yml
    - .tmux.conf
    - .doom.d
  tags:
    - dotfiles
    - emacs
    - spacemacs
    - fastjump
    - tmux

- name: Create ctags config directory
  file:
    state: directory
    dest: ~/.ctags.d/
  tags: [ctags, emacs, spacemacs]

- name: Symlink new ctags config
  file:
    state: link
    src: ~/.dotfiles/.ctags
    dest: ~/.ctags.d/default.ctags
  tags: [ctags, emacs, spacemacs]

- name: Create linux symlinks
  file:
    state: link
    src: "~/.dotfiles/{{ item }}"
    dest: "~/{{ item }}"
  with_items:
    - .keymap.xkb
    - .themes
    - .xsessionrc
  tags: [keyboard]
  when: ansible_os_family == "Archlinux" or ansible_os_family == "Debian"

- name: Check if gitconfig exists
  stat:
    path: ~/.gitconfig
  register: gitconfig_stat
  tags: [git]

- name: Create gitconfig
  copy:
    src: ~/.dotfiles/.gitconfig
    dest: ~/.gitconfig
  when: not gitconfig_stat.stat.exists
  tags: [git]

- name: Create openbox config
  file:
    state: link
    src: "~/.dotfiles/.config/{{ item }}"
    dest: "~/.config/{{ item }}"
  with_items:
    - openbox
    - tint2
  when: ansible_os_family == "Archlinux"

- name: Install Tmux Plugin Mangaer
  git:
    dest: ~/.tmux/plugins/tpm
    repo: "git@github.com:tmux-plugins/tpm.git"
    recursive: yes
    accept_hostkey: yes
    update: no
  tags: [tmux]

- name: Create iex history (otherwise it won't be saved)
  file:
    state: touch
    path: ~/.iex_history
  tags: [iex]
