---
- name: Clone repo
  git:
    dest: ~/.dotfiles
    repo: "git@github.com:mattiaslundberg/dotfiles.git"
    recursive: yes
    accept_hostkey: yes
    update: no

- name: Clone spacemacs repo
  git:
    dest: ~/.emacs.d
    repo: "git@github.com:syl20bnr/spacemacs.git"
    accept_hostkey: yes
    update: no

- name: Create config folders
  file:
    state: directory
    dest: "~/{{ item }}"
  with_items:
    - .config/nvim

- name: Create common symlinks
  file:
    state: link
    src: "~/.dotfiles/{{ item }}"
    dest: "~/{{ item }}"
  with_items:
    - .aliases
    - .bashrc
    - bin
    - .zsh
    - .zprofile
    - .zshrc
    - .colormap
    - .ctags
    - .gitignore_global
    - .hgrc
    - .inputrc
    - .screenrc
    - .sshrc
    - .sshrc.d
    - .vimsnippets
    - .spacemacs
    - .spacemacs.d

- name: Create linux symlinks
  file:
    state: link
    src: "~/.dotfiles/{{ item }}"
    dest: "~/{{ item }}"
  with_items:
    - .keymap.xkb
    - .themes
    - .xsessionrc
  when: ansible_os_family == "Archlinux"

- name: Create nvim config
  file:
    state: link
    src: "~/.dotfiles/.config/nvim/init.vim"
    dest: "~/.config/nvim/init.vim"

- name: Create openbox config
  file:
    state: link
    src: "~/.dotfiles/.config/{{ item }}"
    dest: "~/.config/{{ item }}"
  with_items:
    - openbox
    - tint2
  when: ansible_os_family == "Archlinux"

- name: Install tmux.conf
  template:
    src: tmux.conf.j2
    dest: ~/.tmux.conf
  tags: [tmux]

- name: Install nvim-plug
  shell: nvim +qall! --headless
  args:
    creates: ~/.config/nvim/autoload/plug.vim
  tags: [vim]

- name: Install nvim plugins
  shell: nvim +PlugInstall! +qall! --headless
  tags: [vim]
