---
- name: Clone repo
  git:
    dest: ~/.dotfiles
    repo: "git@github.com:mattiaslundberg/dotfiles.git"
    recursive: yes
    accept_hostkey: yes
    update: no

- name: Clone spacemacs repo
  git:
    dest: ~/.emacs.d
    repo: "git@github.com:syl20bnr/spacemacs.git"
    accept_hostkey: yes
    update: no
    version: develop
  tags: [emacs, spacemacs]

- name: Remove default bashrc
  file:
    state: absent
    dest: ~/.bashrc
  tags: [dotfiles]

- name: Create common symlinks
  file:
    state: link
    src: "~/.dotfiles/{{ item }}"
    dest: "~/{{ item }}"
  with_items:
    - .editorconfig
    - .aliases
    - .bashrc
    - bin
    - .zsh
    - .zprofile
    - .zshrc
    - .gitignore_global
    - .hgrc
    - .inputrc
    - .screenrc
    - .sshrc
    - .sshrc.d
    - .vimsnippets
    - .spacemacs
    - .fastjump.yml
  tags: [emacs, spacemacs, fastjump]

- name: Create ctags config directory
  file:
    state: directory
    dest: ~/.ctags.d/
  tags: [ctags, emacs, spacemacs]

- name: Symlink new ctags config
  file:
    state: link
    src: ~/.dotfiles/.ctags
    dest: ~/.ctags.d/default.ctags
  tags: [ctags, emacs, spacemacs]

- name: Create linux symlinks
  file:
    state: link
    src: "~/.dotfiles/{{ item }}"
    dest: "~/{{ item }}"
  with_items:
    - .keymap.xkb
    - .themes
    - .xsessionrc
  tags: [keyboard]
  when: ansible_os_family == "Archlinux" or ansible_os_family == "Debian"

- name: Create karabiner config directory
  file:
    state: directory
    path: ~/.config/karabiner/
  when:  ansible_os_family == "Darwin"
  tags: [karabiner, keyboard]

- name: Create Karabiner config
  file:
    state: link
    src: ~/.dotfiles/.config/karabiner/{{ item }}
    dest: ~/.config/karabiner/{{ item }}
  with_items:
    - complex_modifications
    - karabiner.json
  when: ansible_os_family == "Darwin"
  tags: [karabiner, keyboard]

- name: Create openbox config
  file:
    state: link
    src: "~/.dotfiles/.config/{{ item }}"
    dest: "~/.config/{{ item }}"
  with_items:
    - openbox
    - tint2
  when: ansible_os_family == "Archlinux"

- name: Install Tmux Plugin Mangaer
  git:
    dest: ~/.tmux/plugins/tpm
    repo: "git@github.com:tmux-plugins/tpm.git"
    recursive: yes
    accept_hostkey: yes
    update: no
  tags: [tmux]

- name: Install tmux.conf
  template:
    src: tmux.conf.j2
    dest: ~/.tmux.conf
  tags: [tmux]

- name: Create iex history (otherwise it won't be saved)
  file:
    state: touch
    path: ~/.iex_history
  tags: [iex]

- name: Create ~/.cache
  file:
    state: directory
    path: ~/.cache
  tags: [dotfiles, fastjump]

- name: Create fastjump visits file
  file:
    state: touch
    path: ~/.cache/fastjump_visits.yml
  tags: [dotfiles, fastjump]
