---
- name: Start emacs daemon
  become: no
  command: brew services start emacs-plus
  tags: [emacs]

- name: Install custom EmacsClient
  become: yes
  tags: [emacs]
  copy:
    dest: /Applications/EmacsClient.app
    src: EmacsClient.app
