---
- name: Clone repo
  git:
    dest: ~/.dotfiles
    repo: "git@github.com:mattiaslundberg/dotfiles.git"
    recursive: yes
    accept_hostkey: yes
    update: no

- name: Clone spacemacs repo
  git:
    dest: ~/.emacs.d
    repo: "git@github.com:syl20bnr/spacemacs.git"
    accept_hostkey: yes
    update: no
  tags: [emacs, spacemacs]

- name: Create common symlinks
  file:
    state: link
    src: "~/.dotfiles/{{ item }}"
    dest: "~/{{ item }}"
  with_items:
    - .editorconfig
    - .aliases
    - .bashrc
    - bin
    - .zsh
    - .zprofile
    - .zshrc
    - .gitignore_global
    - .hgrc
    - .inputrc
    - .screenrc
    - .sshrc
    - .sshrc.d
    - .vimsnippets
    - .spacemacs
  tags: [emacs, spacemacs]

- name: Symlink new ctags config
  file:
    state: link
    src: ~/.dotfiles/.ctags
    dest: ~/.ctags.d/custom.ctags

- name: Create linux symlinks
  file:
    state: link
    src: "~/.dotfiles/{{ item }}"
    dest: "~/{{ item }}"
  with_items:
    - .keymap.xkb
    - .themes
    - .xsessionrc
  when: ansible_os_family == "Archlinux"

- name: Create openbox config
  file:
    state: link
    src: "~/.dotfiles/.config/{{ item }}"
    dest: "~/.config/{{ item }}"
  with_items:
    - openbox
    - tint2
  when: ansible_os_family == "Archlinux"

- name: Install Tmux Plugin Mangaer
  git:
    dest: ~/.tmux/plugins/tpm
    repo: "git@github.com:tmux-plugins/tpm.git"
    recursive: yes
    accept_hostkey: yes
    update: no
  tags: [tmux]

- name: Install tmux.conf
  template:
    src: tmux.conf.j2
    dest: ~/.tmux.conf
  tags: [tmux]

- name: Create iex history (otherwise it won't be saved)
  file:
    state: touch
    path: ~/.iex_history
  tags: [iex]
