---
- name: Restore all packages
  command: brew bundle --file Brewfile

- name: Add brew zsh as allowed shell
  become: yes
  template:
    src: templates/shells.j2
    dest: /etc/shells

- name: Set loginshell
  become: true
  shell: chsh -s /usr/local/bin/zsh

- name: Install python versions
  shell: CFLAGS="-I$(brew --prefix openssl)/include" LDFLAGS="-L$(brew --prefix openssl)/lib" pyenv install {{ item }} -s
  args:
    creates: ~/.pyenv/versions/{{ item }}
  with_items: "{{ pyenv_versions }}"
  tags: [python, install]
