---
- name: Install base packages
  become: true
  pacman:
    name: "{{ item }}"
  with_items:
    - redis
    - memcached
    - neovim
    - tmux
    - nodejs
    - cmake
    - python2
    - python3
    - python-pip
    - the_silver_searcher
    - zsh
    - git
    - openbox
