---
- name: Install base packages
  become: true
  pacman:
    name: "{{ item }}"
    state: "{{ packages_state }}"
    upgrade: yes
  with_items:
    - docker
    - neovim
    - tmux
    - nodejs
    - npm
    - cmake
    - python2
    - python3
    - the_silver_searcher
    - ripgrep
    - emacs
    - zsh
    - git
    - openbox
    - firefox
    - chromium
    - zeal
    - fzf
    - adobe-source-code-pro-fonts
    - mate-terminal
    - emacs
  tags: [install]

- name: Install AUR packages
  command: "pacaur -S --noconfirm --noedit {{ item }}"
  with_items:
    - chkboot
    - entr
    - shutter
    - spotify
    - yarn
    - vagrant-libvirt
    - sshrc-git
    - editorconfig-core-c
    - pyenv
    - pyenv-virtualenv
    - git-extras
    - tmuxinator
  tags: [install, aur]

- name: Install python versions
  shell: pyenv install {{ item }} -s
  args:
    creates: ~/.pyenv/versions/{{ item }}
  with_items: "{{ pyenv_versions }}"
  tags: [python, install]
