---
- name: Install base packages
  become: true
  apt:
    state: present
    name:
      - clang
      - libssl-dev
      - editorconfig
      - rustc
      - entr
      - tldr
      - vim
      - zsh
      - git
      - tmux
      - llvm
  tags: [install]

- name: Set loginshell
  become: true
  shell: "chsh -s /usr/bin/zsh {{ item }}"
  with_items: [vagrant, mattias]
  ignore_errors: true
  tags: [zsh]

- name: Install snaps
  command: "snap install --classic {{ item }}"
  with_items:
    - code
  become: yes
  tags: [install]

- name: Install rust packages
  command: cargo install --force {{ item.name }}
  args:
    creates: ~/.cargo/bin/{{ item.bin }}
  with_items:
    - {"name": "fd-find", "bin": "fd"}
    - {"name": "exa", "bin": "exa"}
    - {"name": "bat", "bin": "bat"}
    - {"name": "--git https://github.com/mattiaslundberg/fastjump.git", "bin": "fastjump"}
  tags: [install]

- name: Fzf
  git:
    dest: ~/.fzf
    repo: "git@github.com:junegunn/fzf.git"
    accept_hostkey: yes
    update: no
  tags: [dotfiles, fzf, install]

- name: Zsh antigen
  git:
    dest: ~/.antigen.zsh
    repo: "git@github.com:zsh-users/antigen.git"
    accept_hostkey: yes
    update: no
  tags: [dotfiles, zsh, install]

- name: Install pyenv
  git:
    dest: ~/.pyenv
    repo: "git@github.com:pyenv/pyenv.git"
    accept_hostkey: yes
    update: no
  tags: [pyenv, install]

- name: Install pyenv-virtualenv
  git:
    dest: ~/.pyenv/plugins/pyenv-virtualenv
    repo: "git@github.com:pyenv/pyenv-virtualenv.git"
    accept_hostkey: yes
    update: no
  tags: [pyenv, install]

- name: Install asdf
  git:
    dest: ~/.asdf
    repo: "git@github.com:asdf-vm/asdf.git"
    accept_hostkey: yes
    update: no
  tags: [asdf, install]

- name: Add Docker GPG apt Key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: [docker, install]

- name: Add Docker Repository
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  tags: [docker, install]

- name: Update apt and install docker-ce
  become: yes
  apt:
    update_cache: yes
    name: docker-ce
    state: latest
  tags: [docker, install]

- name: Create docker group
  become: yes
  group:
    name: docker
  tags: [docker, install]

- name: Add current user to docker group
  become: yes
  user:
    name: "{{ item }}"
    append: yes
    groups:
      - docker
  with_items: [mattias, vagrant]
  tags: [docker, install]

- name: Add emacs Repository
  become: yes
  apt_repository:
    repo: ppa:kelleyk/emacs
    state: present
  tags: [emacs, spacemacs, install]

- name: Install emacs
  become: yes
  apt:
    name: emacs26
    state: present
  tags: [emacs, spacemacs, install]
