---
- name: Install node packages
  npm:
    name: "{{ item }}"
    global: yes
    state: "{{ packages_state }}"
  become: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin/"
  tags: [npm]
  with_items:
    - eslint
    - tern
    - js-beautify

- name: Install asdf plugins
  command: "asdf plugin-add {{ item }}"
  args:
    creates: "~/.asdf/plugins/{{ item }}"
  tags: [asdf]
  with_items:
    - elixir
    - erlang
    - nodejs
    - elm

- name: Fix asdf-nodejs installation
  command: bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
  tags: [asdf]
