---
- name: Restore all packages
  command: brew bundle --file Brewfile

- name: Link openssl
  file:
    path: /usr/local/lib/{{ item }}.dylib
    src: /usr/local/opt/openssl/lib/{{ item }}.dylib
    state: link
  with_items:
    - libssl
    - libcrypto

- name: Add brew zsh as allowed shell
  become: yes
  template:
    src: templates/shells.j2
    dest: /etc/shells

- name: Set loginshell
  become: true
  shell: chsh -s /usr/local/bin/zsh

- name: Install python versions
  shell: pyenv install {{ item }} -s
  args:
    creates: ~/.pyenv/versions/{{ item }}
  with_items: "{{ pyenv_versions }}"
  tags: [python, install]
