---
- name: Tap nvim
  homebrew_tap:
    name: "{{ item }}"
  with_items:
    - universal-ctags/universal-ctags
    - neovim/neovim

- name: Install base packages
  homebrew:
    name: "{{ item }}"
  with_items:
    - mysql
    - redis
    - memcached
    - neovim
    - tmux
    - node
    - yarn
    - editorconfig
    - cmake
    - entr
    - python
    - python3
    - the_silver_searcher
    - zsh
    - git
    - hub
    - reattach-to-user-namespace
    - sshrc

- name: Install ctags
  homebrew:
    install_options: HEAD
    name: universal-ctags
    state: linked

- name: Add brew zsh as allowed shell
  become: true
  template:
    src: templates/shells.j2
    dest: /etc/shells 

- name: Set loginshell
  shell: chsh -s /usr/local/bin/zsh

- name: Tap cask
  homebrew_tap:
    name: caskroom/cask

- name: Install Graphical packages
  homebrew_cask:
    name: "{{ item }}"
  with_items:
    - firefox
    - google-chrome
    - vivaldi
    - dropbox
    - 1password
    - bettertouchtool
    - dash
    - karabiner
    - seil
    - virtualbox
    - sublime-text
    - iterm2
    - java
    - thunderbird
    - spotify

- name: Install pip
  easy_install:
    name: pip
