---
- name: Install node packages
  npm:
    name: "{{ item }}"
    global: yes
    state: "{{ packages_state }}"
  become: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin/"
  tags: [npm]
  with_items:
    - eslint
    - tern
    - js-beautify

- name: Install asdf
  git:
    dest: ~/.asdf
    repo: "git@github.com:asdf-vm/asdf.git"
    recursive: yes
    accept_hostkey: yes
    update: no
  tags: [asdf]

- name: Install asdf plugins
  command: "~/.asdf/bin/asdf plugin-add {{ item.name }} {{ item.repo }}"
  args:
    creates: "~/.asdf/plugins/{{ item.name }}"
  tags: [asdf]
  with_items:
    - {"name": "elixir", "repo": "https://github.com/asdf-vm/asdf-elixir.git"}
    - {"name": "erlang", "repo": "https://github.com/asdf-vm/asdf-erlang.git"}
    - {"name": "nodejs", "repo": "https://github.com/asdf-vm/asdf-nodejs.git"}
    - {"name": "elm", "repo": "https://github.com/vic/asdf-elm.git"}

- name: Install pipsi
  shell: "pyenv shell 2.7.14 && curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python"
  args:
    creates: ~/.local/bin/pipsi
  tags: [pipsi]

- name: Install pipsi packages
  command: pipsi install {{ item }}
  args:
    creates: ~/.local/bin/{{ item }}
  tags: [pipsi]
  with_items:
    - flake8
    - autoflake
    - isort
