---
- name: Install eslint
  npm:
    name: eslint
    global: yes
    state: "{{ packages_state }}"
  become: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin/"

- name: Install gems
  gem:
    name: "{{ item }}"
    state: "{{ packages_state }}"
  become: yes
  with_items:
    - tmuxinator
