---
- name: Install base packages
  become: true
  pacman:
    name: "{{ item }}"
    state: "{{ packages_state }}"
    upgrade: yes
  with_items:
    - mariadb
    - redis
    - memcached
    - neovim
    - tmux
    - nodejs
    - cmake
    - python2
    - python3
    - python-pip
    - the_silver_searcher
    - zsh
    - git
    - openbox
    - firefox
    - chromium
    - zeal
    - fzf
