---
- name: Install base packages
  homebrew:
    name: "{{ item }}"
  with_items:
    - mysql
    - redis
    - memcached
    - neovim
    - tmux
    - node
    - yarn
    - editorconfig
    - cmake
    - entr
    - python
    - python3
    - the_silver_searcher
    - universal-ctags
    - zsh
    - git

- name: Tap cask
  homebrew_tap:
    name: caskroom/cask

- name: Install Graphical packages
  homebrew_cask:
    name: "{{ item }}"
  with_items:
    - firefox
    - google-chrome
    - vivaldi
    - dropbox
    - 1password
    - bettertouchtool
    - dash
    - karabiner
    - seil
    - virtualbox
    - sublime-text
    - iterm2
