---
- name: Tap extra casks
  homebrew_tap:
    name: "{{ item }}"
  with_items:
    - universal-ctags/universal-ctags
    - neovim/neovim
    - caskroom/cask
    - caskroom/fonts

- name: Install gem dependency for ghi
  gem:
    name: pygments.rb

- name: Install base packages
  homebrew:
    name: "{{ item }}"
    state: "{{ packages_state }}"
  with_items:
    - mysql
    - redis
    - memcached
    - neovim
    - tmux
    - node
    - yarn
    - editorconfig
    - cmake
    - entr
    - python
    - python3
    - the_silver_searcher
    - zsh
    - git
    - hub
    - reattach-to-user-namespace
    - sshrc
    - fzf
    - ghi

- name: Install ctags
  homebrew:
    install_options: HEAD
    name: universal-ctags
    state: linked

- name: Add brew zsh as allowed shell
  template:
    src: templates/shells.j2
    dest: /etc/shells

- name: Set loginshell
  become: true
  shell: chsh -s /usr/local/bin/zsh

- name: Install cask packages
  homebrew_cask:
    name: "{{ item }}"
  with_items:
    - firefox
    - google-chrome
    - vivaldi
    - dropbox
    - 1password
    - bettertouchtool
    - dash
    - karabiner-elements
    - virtualbox
    - sublime-text
    - iterm2
    - java
    - thunderbird
    - font-source-code-pro
    - spotify

- name: Install pip
  easy_install:
    name: pip
    state: "{{ packages_state }}"
