---
- name: Add Docker GPG apt Key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: [docker, install]

- name: Add Docker Repository
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  tags: [docker, install]

- name: Install base packages
  become: true
  apt:
    state: present
    name:
      - autoconf
      - build-essential
      - clang
      - cmake
      - cmake
      - curl
      - docker-ce
      - docker-compose
      - editorconfig
      - entr
      - fd-find
      - fish
      - fzf
      - git
      - htop
      - inputplug
      - libpq-dev
      - libsqlite3-dev
      - libssl-dev
      - llvm
      - lm-sensors
      - make
      - neofetch
      - postgresql-client
      - rustc
      - tldr
      - tmux
      - unzip
      - vim
      - xclip
      - zlib1g-dev
      - zsh
    update_cache: yes
  tags: [install]

- name: Autostart inputplug
  template:
    src: templates/inputplug.desktop.j2
    dest: ~/.config/autostart/inputplug.desktop

- name: Symlink fd
  become: true
  file:
    state: link
    src: "/usr/bin/fdfind"
    dest: "/usr/bin/fd"

- name: Set loginshell
  become: true
  shell: "chsh -s /usr/bin/zsh {{ lookup('env', 'USER') }}"
  tags: [zsh]

- name: Install universal-ctags
  become: true
  command: snap install --classic universal-ctags
  tags: [install]

- name: Install emacs
  become: yes
  command: snap install --classic --edge emacs
  tags: [emacs, install]

- name: Install rust packages
  command: cargo install --force {{ item.name }}
  args:
    creates: ~/.cargo/bin/{{ item.bin }}
  with_items:
    - { "name": "exa", "bin": "exa" }
  tags: [install]

- name: Fzf
  git:
    dest: ~/.fzf
    repo: "git@github.com:junegunn/fzf.git"
    accept_hostkey: yes
    update: no
  tags: [dotfiles, fzf, install]

- name: Zsh antigen
  git:
    dest: ~/.antigen.zsh
    repo: "git@github.com:zsh-users/antigen.git"
    accept_hostkey: yes
    update: no
  tags: [dotfiles, zsh, install]

- name: Install asdf
  git:
    dest: ~/.asdf
    repo: "git@github.com:asdf-vm/asdf.git"
    accept_hostkey: yes
    update: no
  tags: [asdf, install]

- name: Create docker group
  become: yes
  group:
    name: docker
  tags: [docker, install]

- name: Add current user to docker group
  become: yes
  user:
    name: "{{ lookup('env', 'USER') }}"
    append: yes
    groups:
      - docker
  tags: [docker, install]

- name: reset ssh connection to allow user changes to affect 'current login user'
  meta: reset_connection
