---
- name: Install asdf plugins
  command: "asdf plugin-add {{ item }}"
  args:
    creates: "~/.asdf/plugins/{{ item }}"
  tags: [asdf]
  with_items:
    - elixir
    - erlang
    - nodejs
    - elm
    - terraform
    - terragrunt

- name: Fix asdf-nodejs installation
  command: bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
  tags: [asdf]
