---
- name: Tap extra casks
  homebrew_tap:
    name: "{{ item }}"
  with_items:
    - universal-ctags/universal-ctags
    - neovim/neovim
    - caskroom/cask
    - caskroom/fonts

- name: Install gem dependency for ghi
  gem:
    name: pygments.rb

- name: Install base packages
  homebrew:
    name: "{{ item }}"
    state: "{{ packages_state }}"
  with_items:
    - docker
    - neovim
    - tmux
    - node
    - yarn
    - editorconfig
    - cmake
    - entr
    - python
    - python3
    - pyenv
    - pyenv-virtualenv
    - the_silver_searcher
    - zsh
    - git
    - git-extras
    - hub
    - ghi
    - reattach-to-user-namespace
    - sshrc
    - fzf

- name: Install emacs
  homebrew:
    name: emacs
    install_options: "--with-cocoa"

- name: Install ctags
  homebrew:
    install_options: HEAD
    name: universal-ctags
    state: present

- name: Link ctags
  homebrew:
    install_options: HEAD
    name: universal-ctags
    state: linked

- name: Add brew zsh as allowed shell
  become: yes
  template:
    src: templates/shells.j2
    dest: /etc/shells

- name: Set loginshell
  become: true
  shell: chsh -s /usr/local/bin/zsh

- name: Install cask packages
  homebrew_cask:
    name: "{{ item }}"
  with_items:
    - firefox
    - google-chrome
    - dropbox
    - 1password
    - bettertouchtool
    - dash
    - karabiner-elements
    - virtualbox
    - sublime-text
    - iterm2
    - thunderbird
    - spotify

- name: Install font packages
  homebrew_cask:
    name: "{{ item }}"
    install_options: "--fontdir=/Library/Fonts"
  with_items:
    - font-source-code-pro

- name: Install pip
  become: yes
  easy_install:
    name: pip
    state: "{{ packages_state }}"

- name: Install gems
  gem:
    name: "{{ item }}"
    state: "{{ packages_state }}"
  become: yes
  with_items:
    - tmuxinator
