---
- name: Install base packages
  become: true
  pacman:
    name: "{{ item }}"
    state: "{{ packages_state }}"
    upgrade: yes
  with_items:
    - mariadb
    - redis
    - memcached
    - neovim
    - tmux
    - nodejs
    - npm
    - cmake
    - python2
    - python3
    - python-pip
    - the_silver_searcher
    - zsh
    - git
    - openbox
    - firefox
    - chromium
    - zeal
    - fzf
    - adobe-source-code-pro-fonts
    - mate-terminal
  tags: [install]

- name: Install AUR packages
  command: "pacaur -S --noconfirm --noedit {{ item }}"
  with_items:
    - chkboot
    - entr
    - shutter
    - spotify
    - yarn
    - vagrant-libvirt
    - sshrc-git
    - editorconfig-core-c
    - pyenv
    - pyenv-virtualenv
  tags: [install, aur]
