---
  - name: Install base packages
    homebrew:
      name: "{{ item }}"
      state: latest
    with_items:
      - mysql
      - redis
      - memcached
      - neovim
      - tmux
      - node
      - yarn
      - editorconfig
      - cmake
      - entr
      - python
      - python3
      - the_silver_searcher
      - universal-ctags
      - zsh

  - name: Set shell
    command: echo "Fixme"

  - name: Install tmuxinator
    gem:
      name: tmuxinator
      state: latest

  - name: Install eslint
    npm:
      name: eslint
      global: yes
      state: latest

  - name: Install pip
    easy_install:
      name: pip

    - name: Install python packages
      pip:
        name: "{{ item }}"
        state: latest
      with_items:
        - virtualenvwrapper
        - isort
        - neovim
        - flake8
