---
- name: Install python2 only packages
  pip:
    name: "{{ item }}"
  with_items:
    - virtualenvwrapper
    - pex

- name: Install python2 packages
  pip:
    name: "{{ item }}"
    executable: pip
  with_items: "{{ pip_packages }}"
  when: ansible_os_family != "Archlinux"

- name: Install python3 packages
  pip:
    name: "{{ item }}"
    executable: pip3
  with_items: "{{ pip_packages }}"

- name: Setup virtualenvwrapper scripts
  template:
    src: templates/{{ item }}.j2
    dest: ~/.virtualenvs/{{ item }}
    mode: o=rwx,g=rx
  with_items:
    - postmkvirtualenv
