---
- name: Install pyenv
  git:
    dest: ~/.pyenv
    repo: "git@github.com:pyenv/pyenv.git"
    accept_hostkey: yes
    update: no

- name: Install pyenv-virtualenv
  git:
    dest: ~/.pyenv/plugins/pyenv-virtualenv
    repo: "git@github.com:pyenv/pyenv-virtualenv.git"
    accept_hostkey: yes
    update: no

- name: Install python versions
  shell: pyenv install {{ item }} -s
  args:
    creates: ~/.pyenv/versions/{{ item }}
  with_items: "{{ pyenv_versions }}"
  ignore_errors: yes
