---
- name: Install main python only packages
  become: yes
  pip:
    name: "{{ item }}"
    state: "{{ packages_state }}"
  tags: [python]
  with_items:
    - pex
    - requests

- name: Install python2 packages
  become: yes
  pip:
    name: "{{ item }}"
    executable: pip
    state: "{{ packages_state }}"
  tags: [python]
  with_items: "{{ pip_packages }}"

- name: Install python3 packages
  pip:
    name: "{{ item }}"
    executable: pip3
    state: "{{ packages_state }}"
  tags: [python]
  with_items: "{{ pip_packages }}"
