---
- name: Install pyenv
  git:
    dest: ~/.pyenv
    repo: "git@github.com:pyenv/pyenv.git"
    accept_hostkey: yes
    update: no

- name: Install pyenv-virtualenv
  git:
    dest: ~/.pyenv/plugins/pyenv-virtualenv
    repo: "git@github.com:pyenv/pyenv-virtualenv.git"
    accept_hostkey: yes
    update: no
