---
- name: Create folder for cloning {{ package_name }}
  become: true
  file:
    state: directory
    path: /usr/local/share/aur/
    owner: "{{ ansible_user_id }}"

- name: Clone/update repo {{ package_name }}
  git:
    repo: https://aur.archlinux.org/{{ package_name }}.git
    dest: /usr/local/share/aur/{{ package_name }}
    force: yes

- name: Get latest version of {{ package_name }}
  shell: grep pkgver= PKGBUILD | cut -d = -f 2
  args:
    chdir: /usr/local/share/aur/{{ package_name }}
  register: new_version

- name: Get latest revision of {{ package_name }}
  shell: grep pkgrel= PKGBUILD | cut -d = -f 2
  args:
    chdir: /usr/local/share/aur/{{ package_name }}
  register: new_rel

- name: Build the package {{ package_name }}
  command: makepkg -s
  args:
    chdir: /usr/local/share/aur/{{ package_name }}
    creates: /usr/local/share/aur/{{ package_name }}/{{ package_name }}-{{ new_version.stdout }}-{{ new_rel.stdout }}-*.pkg.tar.xz
  register: build_status
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/bin/core_perl/"

- name: Install the package {{ package_name }}
  become: yes
  when: build_status.changed
  shell: pacman --noconfirm -U /usr/local/share/aur/{{ package_name }}/{{ package_name }}-{{ new_version.stdout }}-{{ new_rel.stdout }}-*.pkg.tar.xz
