---
- name: Create folder for cloning {{ package_name }}
  become: true
  file:
    state: directory
    path: /usr/local/share/aur/
    owner: "{{ ansible_user_id }}"

- name: Clone/update repo {{ package_name }}
  git:
    repo: https://aur.archlinux.org/{{ package_name }}.git
    dest: /usr/local/share/aur/{{ package_name }}
    force: yes

- name: Get last revision {{ package_name }}
  command: cat last_revision.txt
  args:
    chdir: /usr/local/share/aur/{{ package_name }}
  ignore_errors: yes
  register: last_revision

- name: Get new revision {{ package_name }}
  command: git rev-parse @
  args:
    chdir: /usr/local/share/aur/{{ package_name }}
  register: new_revision

- name: Build the package {{ package_name }}
  command: makepkg -s
  args:
    chdir: /usr/local/share/aur/{{ package_name }}
  when: last_revision.stdout != new_revision.stdout
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/bin/core_perl/"

- name: Install the package {{ package_name }}
  become: yes
  shell: pacman --noconfirm -U /usr/local/share/aur/{{ package_name }}/*.pkg.tar.xz

- name: Write last revision to file {{ package_name }}
  copy:
    dest: /usr/local/share/aur/{{ package_name }}/last_revision.txt
    content: "{{ new_revision.stdout }}"
