---
- name: Add keymap
  become: true
  copy:
    dest: /Library/Keyboard Layouts/Custom Layout.bundle/
    src: roles/keyboard/files/keymap/
  tags: [keyboard, keymap]
  when: ansible_os_family == "Darwin"

- name: Disable annoying keyboard settings
  osx_defaults:
    domain: NSGlobalDomain
    key: "{{ item }}"
    type: bool
    value: false
  with_items:
    - NSAutomaticCapitalizationEnabled
    - NSAutomaticDashSubstitutionEnabled
    - NSAutomaticPeriodSubstitutionEnabled
    - NSAutomaticQuoteSubstitutionEnabled
    - NSAutomaticSpellingCorrectionEnabled
  when: ansible_os_family == "Darwin"

- name: Enable full keyboard access
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleKeyboardUIMode
    type: int
    value: 3
  when: ansible_os_family == "Darwin"
