---
- name: Add Docker GPG apt Key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: [docker, install]
  when: ansible_os_family == "Debian"

- name: Add Docker Repository
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  tags: [docker, install]
  when: ansible_os_family == "Debian"

- name: Update apt and install docker-ce
  become: yes
  apt:
    update_cache: yes
    name:
      - docker-ce
      - docker-compose
    state: latest
  tags: [docker, install]
  when: ansible_os_family == "Debian"

- name: Create docker group
  become: yes
  group:
    name: docker
  tags: [docker, install]
  when: ansible_os_family == "Debian"

- name: Add current user to docker group
  become: yes
  user:
    name: "{{ lookup('env', 'USER') }}"
    append: yes
    groups:
      - docker
  tags: [docker]
  when: ansible_os_family == "Debian"
