---
- name: Create custom brew cache
  become: yes
  file:
    state: directory
    path: /opt/HomebrewCache
    owner: mattias

- name: Install base packages
  homebrew:
    name:
      - zsh # Changing shell
      - curl # Installing
      - luarocks # Spacehammer/fennel
      - antigen # Shell config
    state: present

- name: Restore all packages
  command: brew bundle --file=Brewfile
  tags: [brew, extra]

- name: Link emacs
  become: yes
  file:
    state: link
    src: /opt/homebrew/opt/emacs-plus@28/Emacs.app
    dest: /Applications/Emacs.app

# - name: Link openssl
#   file:
#     path: /usr/local/lib/{{ item }}.dylib
#     src: /usr/local/opt/openssl/lib/{{ item }}.dylib
#     state: link
#   with_items:
#     - libssl
#     - libcrypto

- name: Add brew zsh as allowed shell
  become: yes
  template:
    src: templates/shells.j2
    dest: /etc/shells
  tags: [zsh]

- name: Set loginshell
  become: true
  shell: chsh -s /opt/homebrew/bin/zsh
  tags: [zsh]
